# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui',
# licensing of 'preferences.ui' applies.
#
# Created: Fri Mar 29 10:05:34 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(390, 270)
        Dialog.setMinimumSize(QtCore.QSize(390, 270))
        Dialog.setMaximumSize(QtCore.QSize(390, 270))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/prefs.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.preferences = QtWidgets.QDialogButtonBox(Dialog)
        self.preferences.setGeometry(QtCore.QRect(27, 240, 341, 20))
        self.preferences.setOrientation(QtCore.Qt.Horizontal)
        self.preferences.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.preferences.setObjectName("preferences")
        self.PREFUseExternalDB = QtWidgets.QCheckBox(Dialog)
        self.PREFUseExternalDB.setGeometry(QtCore.QRect(20, 20, 131, 20))
        self.PREFUseExternalDB.setObjectName("PREFUseExternalDB")
        self.PREFDisableWindowsLongPathSupport = QtWidgets.QCheckBox(Dialog)
        self.PREFDisableWindowsLongPathSupport.setGeometry(QtCore.QRect(20, 180, 251, 20))
        self.PREFDisableWindowsLongPathSupport.setObjectName("PREFDisableWindowsLongPathSupport")
        self.PREFMaxSearchResults = QtWidgets.QSpinBox(Dialog)
        self.PREFMaxSearchResults.setGeometry(QtCore.QRect(250, 50, 121, 20))
        self.PREFMaxSearchResults.setMinimum(10)
        self.PREFMaxSearchResults.setMaximum(999999999)
        self.PREFMaxSearchResults.setObjectName("PREFMaxSearchResults")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 231, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 91, 20))
        self.label_2.setObjectName("label_2")
        self.PREFLoggingLevel = QtWidgets.QComboBox(Dialog)
        self.PREFLoggingLevel.setGeometry(QtCore.QRect(120, 110, 81, 20))
        self.PREFLoggingLevel.setObjectName("PREFLoggingLevel")
        self.PREFLoggingLevel.addItem("")
        self.PREFLoggingLevel.addItem("")
        self.PREFLoggingLevel.addItem("")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 151, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(236, 80, 40, 20))
        self.label_4.setObjectName("label_4")
        self.PREFSaveRemovedInfoDays = QtWidgets.QSpinBox(Dialog)
        self.PREFSaveRemovedInfoDays.setGeometry(QtCore.QRect(170, 80, 61, 20))
        self.PREFSaveRemovedInfoDays.setMinimum(0)
        self.PREFSaveRemovedInfoDays.setMaximum(999999999)
        self.PREFSaveRemovedInfoDays.setProperty("value", 0)
        self.PREFSaveRemovedInfoDays.setObjectName("PREFSaveRemovedInfoDays")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 261, 20))
        self.label_5.setObjectName("label_5")
        self.PREFsqlTransactionLimit = QtWidgets.QSpinBox(Dialog)
        self.PREFsqlTransactionLimit.setGeometry(QtCore.QRect(290, 210, 81, 20))
        self.PREFsqlTransactionLimit.setMinimum(1)
        self.PREFsqlTransactionLimit.setMaximum(999999999)
        self.PREFsqlTransactionLimit.setProperty("value", 1)
        self.PREFsqlTransactionLimit.setObjectName("PREFsqlTransactionLimit")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 130, 391, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 331, 20))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.preferences, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.preferences, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.PREFUseExternalDB, self.PREFMaxSearchResults)
        Dialog.setTabOrder(self.PREFMaxSearchResults, self.PREFSaveRemovedInfoDays)
        Dialog.setTabOrder(self.PREFSaveRemovedInfoDays, self.PREFLoggingLevel)
        Dialog.setTabOrder(self.PREFLoggingLevel, self.PREFDisableWindowsLongPathSupport)
        Dialog.setTabOrder(self.PREFDisableWindowsLongPathSupport, self.PREFsqlTransactionLimit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.PREFUseExternalDB.setText(QtWidgets.QApplication.translate("Dialog", "Use MySQL", None, -1))
        self.PREFDisableWindowsLongPathSupport.setText(QtWidgets.QApplication.translate("Dialog", "Disable Windows long path support", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Maximum search results by default: ", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Logging level:", None, -1))
        self.PREFLoggingLevel.setItemText(0, QtWidgets.QApplication.translate("Dialog", "DEBUG", None, -1))
        self.PREFLoggingLevel.setItemText(1, QtWidgets.QApplication.translate("Dialog", "INFO", None, -1))
        self.PREFLoggingLevel.setItemText(2, QtWidgets.QApplication.translate("Dialog", "WARNING", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Save removed files info", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "day(s)", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" color:#000000;\">MySQL update limit (files per transaction):</span></p></body></html>", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p>These settings should remain default in most cases.</p></body></html>", None, -1))

import icons_rc
